### PR TITLE
comply with predtimechart 2.0.11

### LINKED ISSUE #22: Update schema to comply with predtimechart 2.0.11
I [ran into an error](https://github.com/hubverse-org/hub-dashboard-control-room/actions/runs/11672076677/job/32499906801) when attempting to build JSON files with a YAML schema that omitted the "disclaimer" element:

<details><summary>Error output</summary>
<p>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.7/x64/bin/ptc_generate_json_files", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/hub_predtimechart/app/generate_json_files.py", line 48, in main
    hub_config = HubConfig(Path(hub_dir), Path(ptc_config_file))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/hub_predtimechart/hub_config.py", line 48, in __init__
    raise RuntimeError(f"invalid ptc_config_file. error='{ve}'")
RuntimeError: invalid ptc_config_file. error=''disclaimer' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     '$id': 'https://github.com/reichlab/hub-dashboard-predtimechart/src/hub_predtimechart/schema.json',
     'title': 'predtimechart options',
     'description': 'hub predtimechart configuration object schema',
     'type': 'object',
     'additionalProperties': False,
     'properties': {'rounds_idx': {'description': '0-based index of the '
                                                  '`rounds` entry to use '
                                                  'for visualization',
                                   'type': 'integer',
                                   'minimum': 0},
                    'model_tasks_idx': {'description': '0-based index of '
                                                       'the `model_tasks` '
                                                       'entry under '
                                                       '`rounds_idx` to '
                                                       'use for '
                                                       'visualization',
                                        'type': 'integer',
                                        'minimum': 0},
                    'reference_date_col_name': {'description': 'name of '
                                                               'the column '
                                                               'that '
                                                               'represents '
                                                               'the '
                                                               '`reference_date`',
                                                'type': 'string',
                                                'minLength': 1},
                    'target_date_col_name': {'description': 'name of the '
                                                            'column that '
                                                            'represents '
                                                            'the '
                                                            '`target_date`',
                                             'type': 'string',
                                             'minLength': 1},
                    'horizon_col_name': {'description': 'name of the '
                                                        'column that '
                                                        'represents the '
                                                        '`horizon`',
                                         'type': 'string',
                                         'minLength': 1},
                    'initial_checked_models': {'description': 'models '
                                                              'id(s) to '
                                                              'use for the '
                                                              'initial '
                                                              'plot',
                                               'type': 'array',
                                               'uniqueItems': True,
                                               'items': {'type': 'string'}},
                    'disclaimer': {'description': 'text providing any '
                                                  'important information '
                                                  'users should know',
                                   'type': 'string',
                                   'minLength': 1}},
     'required': ['rounds_idx',
                  'model_tasks_idx',
                  'reference_date_col_name',
                  'target_date_col_name',
                  'horizon_col_name',
                  'initial_checked_models',
                  'disclaimer']}

On instance:
    {'rounds_idx': 0,
     'model_tasks_idx': 1,
     'reference_date_col_name': 'reference_date',
     'target_date_col_name': 'target_end_date',
     'horizon_col_name': 'horizon',
     'initial_checked_models': ['UMass-flusion', 'UMass-trends_ensemble']}'
```

</p>
</details> 

The issue can be fixed by modifying two files:

1. remove `disclaimer` from the required elements in `src/hub_predtimechart/ptc_schema.py`:
   https://github.com/hubverse-org/hub-dashboard-predtimechart/blob/ede9b51ce075840a2aa5d00080bbcf4152da3fb2/src/hub_predtimechart/ptc_schema.py#L48-L56
2. Change `ptc_config['disclaimer']` to `ptc_config.get('disclaimer')` in `src/hub_predtimechart/hub_config.py` so that it returns `None` instead of a KeyError. 
   https://github.com/hubverse-org/hub-dashboard-predtimechart/blob/ede9b51ce075840a2aa5d00080bbcf4152da3fb2/src/hub_predtimechart/hub_config.py#L61

### PR DESCRIPTION
**Pull request by zkamvar**
This is my proposal to address #22. Feel free to close if this is not up to your standards for code and test style.

Note that I wrote the tests to use an extra config file for an existing test hub instead of duplicating hubs. I have also added contents from #23 and add Matt as an author on that commit.

Merging this will fix #22.

### CODE REVIEW

**Review by matthewcornell — CHANGES_REQUESTED** [review]
Thanks for doing this, Zhian. It looks pretty good to me. Comments:

- test_hub_config_complex_forecast_hub_no_disclaimer(): In this case, since other tests cover non-disclamer code, I suggest this test simply does lines 49, 50, and 58, i.e.,
```python
def test_hub_config_complex_forecast_hub_no_disclaimer():
    hub_dir = Path('tests/hubs/example-complex-forecast-hub')
    hub_config = HubConfig(hub_dir, Path('tests/configs/example-complex-no-disclaimer.yml'))
    assert hub_config.disclaimer == None
```
- formatting: I'm pretty particular with respect to formatting (line breaks in this case), but how about I tighten them up in a separate PR?

**Comment by zkamvar** [comment]
> * test_hub_config_complex_forecast_hub_no_disclaimer(): In this case, since other tests cover non-disclamer code, I suggest this test simply does lines 49, 50, and 58, i.e.,

Sounds good to me! I'll go ahead and clean that up.

> * formatting: I'm pretty particular with respect to formatting (line breaks in this case), but how about I tighten them up in a separate PR?

I think that sounds good 🧹

**Review by matthewcornell — CHANGES_REQUESTED** [review]
Looks good, but one thing that's missing is actually changing `ptc_options_for_hub()` in `src/hub_predtimechart/generate_options.py` to only set the disclaimer if present. I.e., it should look like:

```python
def ptc_options_for_hub(hub_config: HubConfig):
    # ...
    # add `disclaimer` if present
    if hub_config.disclaimer is not None:
        options['disclaimer'] = hub_config.disclaimer
```

**Comment by zkamvar** [comment]
> Looks good, but one thing that's missing is actually changing `ptc_options_for_hub()` in `src/hub_predtimechart/generate_options.py` to only set the disclaimer if present. (Otherwise it will pass None to predtimechart, which is invalid.) It needs a test too. I.e., it should look like:

Good catch!

**Review by matthewcornell — APPROVED** [review]
Yay!

**Pull request merged**
